jianglindian_lanuch-1=科技文明与修仙文明，不过是宇宙在漫长遗忘中，偶然翻涌起的两朵浪花。
jianglindian_lanuch-2=科技文明在无尽的征服与建造中，试图用物质的堆积来唤醒那沉睡的完整
jianglindian_lanuch-3=他们造出能撕裂维度的战舰，造出能演算过去未来的机器，造出能覆盖整个星系的网络。
jianglindian_lanuch-4=他们以为，只要收集足够多的碎片，就能拼出造物主最初的模样。
jianglindian_lanuch-5=而修行文明将万物融归于混沌的源头，以感悟为丝线重新编织，借因果作经纬，织就名为“修行”的无尽长卷
jianglindian_lanuch-6=他们闭关千年，在识海深处打捞沉没的往昔；他们历劫万载，在生死轮回中擦拭被尘埃蒙蔽的本真。
jianglindian_lanuch-7=他们御风而行，不是征服风，而是记起自己曾是风；他们移山填海，不是命令山，而是记起自己曾是山。
jianglindian_lanuch-8=他们只相信内证，相信只要足够安静，足够纯粹，就能听见那来自造物主的古老回响。
jianglindian_lanuch-9=科技文明称造物主为规律，修行文明称造物主为大道
jianglindian_lanuch-10=随着宇宙变迁，两种截然不同的文明也开始了碰撞